# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4305049c0d2a77089208bb70e0132e8804ad5923972a0f2fd998731951587def20a5d90a7edac7532dbb776a868ea6d256e9dade01da40fed59fd351338e168

test:
  secret_key_base: 2c1fe9e43d7c1e9f94c45f52820bf18ef604e6c746dd7c384efd38436d3be83a5f434d6688ed2e1dfb9fc170bbebbd72f9f185d061423004f4552f020e6c4f93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
